# Generated by Django 3.2.18 on 2023-04-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lms_user_id',
            field=models.IntegerField(blank=True, help_text='The auth.User.id value of the corresponding user in edx-platform.', null=True),
        ),
    ]
