# Generated by Django 3.2.19 on 2023-09-15 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_extensions.db.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplicatedContentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('enterprise_customer_uuid', models.UUIDField(db_index=True, editable=False)),
                ('content_key', models.CharField(db_index=True, editable=False, help_text='The globally unique content identifier for this course.  Joinable with ContentMetadata.content_key in enterprise-catalog.', max_length=255)),
                ('content_type', models.CharField(db_index=True, help_text='The type of content (e.g. course or courserun).', max_length=255)),
                ('raw_metadata', models.JSONField(help_text='The raw JSON metadata fetched from the enterprise-catalog customer metadata API.')),
                ('raw_fetched_at', models.DateTimeField(editable=False, help_text='Time at which raw_metadata was last fetched.')),
                ('title', models.CharField(help_text='The title of the course', max_length=2047, null=True)),
                ('price', models.BigIntegerField(help_text='Cost of this course run in USD Cents.')),
                ('product_source', models.CharField(db_index=True, help_text='The product source for this course.', max_length=255, null=True)),
                ('course_mode', models.CharField(db_index=True, help_text='The enrollment mode supported for this course.', max_length=255, null=True)),
            ],
            options={
                'unique_together': {('enterprise_customer_uuid', 'content_key')},
            },
            managers=[
                ('recent_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalReplicatedContentMetadata',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('enterprise_customer_uuid', models.UUIDField(db_index=True, editable=False)),
                ('content_key', models.CharField(db_index=True, editable=False, help_text='The globally unique content identifier for this course.  Joinable with ContentMetadata.content_key in enterprise-catalog.', max_length=255)),
                ('content_type', models.CharField(db_index=True, help_text='The type of content (e.g. course or courserun).', max_length=255)),
                ('raw_metadata', models.JSONField(help_text='The raw JSON metadata fetched from the enterprise-catalog customer metadata API.')),
                ('raw_fetched_at', models.DateTimeField(editable=False, help_text='Time at which raw_metadata was last fetched.')),
                ('title', models.CharField(help_text='The title of the course', max_length=2047, null=True)),
                ('price', models.BigIntegerField(help_text='Cost of this course run in USD Cents.')),
                ('product_source', models.CharField(db_index=True, help_text='The product source for this course.', max_length=255, null=True)),
                ('course_mode', models.CharField(db_index=True, help_text='The enrollment mode supported for this course.', max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical replicated content metadata',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
