# Generated by Django 3.2.17 on 2023-02-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnercreditsubsidy',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionsubsidy',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='learnercreditsubsidy',
            name='customer_uuid',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='subscriptionsubsidy',
            name='customer_uuid',
            field=models.UUIDField(db_index=True),
        ),
        migrations.DeleteModel(
            name='LearnerCreditAccessPolicy',
        ),
        migrations.DeleteModel(
            name='LicenseRequestAccessPolicy',
        ),
        migrations.DeleteModel(
            name='PerLearnerEnrollmentCapLearnerCreditAccessPolicy',
        ),
        migrations.DeleteModel(
            name='SubscriptionAccessPolicy',
        ),
    ]
