# Generated by Django 3.2.17 on 2023-02-08 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0002_remove_subsidy_fields_20230208_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perlearnerenrollmentcaplearnercreditaccesspolicy',
            name='learnercreditaccesspolicy_ptr',
        ),
        migrations.DeleteModel(
            name='LicenseRequestAccessPolicy',
        ),
        migrations.DeleteModel(
            name='PerLearnerEnrollmentCapLearnerCreditAccessPolicy',
        ),
    ]
