# Generated by Django 3.2.17 on 2023-02-08 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0003_remove_some_access_policy_models_20230208_0057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearnerCreditAccessPolicy',
        ),
        migrations.DeleteModel(
            name='SubscriptionAccessPolicy',
        ),
    ]
