# Generated by Django 3.2.17 on 2023-02-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0004_remove_rest_of_access_policy_models_20230208_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnercreditsubsidy',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionsubsidy',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='learnercreditsubsidy',
            name='customer_uuid',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='subscriptionsubsidy',
            name='customer_uuid',
            field=models.UUIDField(db_index=True),
        ),
    ]
