# Generated by Django 3.2.17 on 2023-02-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0005_add_subsidy_fields_20230208_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnercreditsubsidy',
            old_name='customer_uuid',
            new_name='enterprise_customer_uuid',
        ),
        migrations.RenameField(
            model_name='learnercreditsubsidy',
            old_name='opportunity_id',
            new_name='reference_id',
        ),
        migrations.RenameField(
            model_name='subscriptionsubsidy',
            old_name='customer_uuid',
            new_name='enterprise_customer_uuid',
        ),
        migrations.RenameField(
            model_name='subscriptionsubsidy',
            old_name='opportunity_id',
            new_name='reference_id',
        ),
        migrations.AddField(
            model_name='learnercreditsubsidy',
            name='reference_type',
            field=models.CharField(choices=[('opportunity_product_id', 'Opportunity Product ID')], db_index=True, default='opportunity_product_id', max_length=255),
        ),
        migrations.AddField(
            model_name='subscriptionsubsidy',
            name='reference_type',
            field=models.CharField(choices=[('opportunity_product_id', 'Opportunity Product ID')], db_index=True, default='opportunity_product_id', max_length=255),
        ),
    ]
