# Generated by Django 3.2.18 on 2023-02-21 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0008_enterprisesubsidyfeaturerole_enterprisesubsidyroleassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallearnercreditsubsidy',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallearnercreditsubsidy',
            name='ledger',
        ),
        migrations.RemoveField(
            model_name='historicalsubscriptionsubsidy',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsubscriptionsubsidy',
            name='ledger',
        ),
        migrations.RemoveField(
            model_name='learnercreditsubsidy',
            name='ledger',
        ),
        migrations.RemoveField(
            model_name='subscriptionsubsidy',
            name='ledger',
        ),
        migrations.DeleteModel(
            name='HistoricalLearnerCreditSubsidy',
        ),
        migrations.DeleteModel(
            name='HistoricalSubscriptionSubsidy',
        ),
        migrations.DeleteModel(
            name='LearnerCreditSubsidy',
        ),
        migrations.DeleteModel(
            name='SubscriptionSubsidy',
        ),
    ]
