# Generated by Troy :)

from django.db import migrations

from enterprise_subsidy.apps.subsidy.constants import (
    ENTERPRISE_SUBSIDY_LEARNER_ROLE,
    ENTERPRISE_SUBSIDY_ADMIN_ROLE,
    ENTERPRISE_SUBSIDY_OPERATOR_ROLE,
)


def create_roles(apps, schema_editor):
    """
    Create the feature roles if they do not already exist.
    """
    EnterpriseSubsidyFeatureRole = apps.get_model('subsidy', 'EnterpriseSubsidyFeatureRole')
    EnterpriseSubsidyFeatureRole.objects.update_or_create(name=ENTERPRISE_SUBSIDY_LEARNER_ROLE)
    EnterpriseSubsidyFeatureRole.objects.update_or_create(name=ENTERPRISE_SUBSIDY_ADMIN_ROLE)
    EnterpriseSubsidyFeatureRole.objects.update_or_create(name=ENTERPRISE_SUBSIDY_OPERATOR_ROLE)


def delete_roles(apps, schema_editor):
    """
    Delete the feature roles.
    """
    EnterpriseSubsidyFeatureRole = apps.get_model('subsidy', 'EnterpriseSubsidyFeatureRole')
    EnterpriseSubsidyFeatureRole.objects.filter(name=ENTERPRISE_SUBSIDY_LEARNER_ROLE).delete()
    EnterpriseSubsidyFeatureRole.objects.filter(name=ENTERPRISE_SUBSIDY_ADMIN_ROLE).delete()
    EnterpriseSubsidyFeatureRole.objects.filter(name=ENTERPRISE_SUBSIDY_OPERATOR_ROLE).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0010_historicalsubsidy_subsidy'),
    ]

    operations = [
        migrations.RunPython(create_roles, delete_roles),
    ]
