# Generated by Django 3.2.18 on 2023-03-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0011_seed_feature_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubsidy',
            name='internal_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subsidy',
            name='internal_only',
            field=models.BooleanField(default=False),
        ),
    ]
