# Generated by Django 3.2.18 on 2023-03-13 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_ledger', '0003_field_updates_20230216_1605'),
        ('subsidy', '0012_auto_20230302_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidy',
            name='ledger',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidy', to='openedx_ledger.ledger'),
        ),
    ]
