# Generated by Django 3.2.18 on 2023-03-15 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0013_alter_subsidy_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubsidy',
            name='unit',
            field=models.CharField(choices=[('usd_cents', 'U.S. Dollar (Cents)'), ('seats', 'Seats in a course')], db_index=True, default='usd_cents', max_length=255),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='ledger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='openedx_ledger.ledger'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='unit',
            field=models.CharField(choices=[('usd_cents', 'U.S. Dollar (Cents)'), ('seats', 'Seats in a course')], db_index=True, default='usd_cents', max_length=255),
        ),
    ]
