# Generated by Django 3.2.20 on 2023-09-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0016_sf_opp_line_item_20230404_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subsidy',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='historicalsubsidy',
            name='is_soft_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='If set, this subsidy will be considered as soft-deleted or deactivated.'),
        ),
        migrations.AddField(
            model_name='subsidy',
            name='is_soft_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='If set, this subsidy will be considered as soft-deleted or deactivated.'),
        ),
        migrations.AlterField(
            model_name='historicalsubsidy',
            name='active_datetime',
            field=models.DateTimeField(default=None, help_text='The datetime when this Subsidy is considered active.  If null, this Subsidy is considered inactive.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalsubsidy',
            name='expiration_datetime',
            field=models.DateTimeField(default=None, help_text='The datetime when this Subsidy is considered expired.  If null, this Subsidy is considered active.', null=True),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='active_datetime',
            field=models.DateTimeField(default=None, help_text='The datetime when this Subsidy is considered active.  If null, this Subsidy is considered inactive.', null=True),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='expiration_datetime',
            field=models.DateTimeField(default=None, help_text='The datetime when this Subsidy is considered expired.  If null, this Subsidy is considered active.', null=True),
        ),
    ]
