# Generated by Django 3.2.21 on 2023-09-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0017_add_is_soft_deleted_subsidy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsubsidy',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical subsidy', 'verbose_name_plural': 'historical subsidys'},
        ),
    ]
