# Generated by Django 3.2.19 on 2023-10-31 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0018_alter_historicalsubsidy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsubsidy',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical subsidy'},
        ),
    ]
