# Generated by Django 3.2.19 on 2023-10-31 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0019_alter_historicalsubsidy_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subsidy',
            name='unique_reference_id_non_internal',
        ),
    ]
