# Generated by Django 5.2.3 on 2025-06-25 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy', '0022_backfill_initial_deposits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsubsidy',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Subsidy', 'verbose_name_plural': 'historical Subsidies'},
        ),
        migrations.AlterModelOptions(
            name='subsidy',
            options={'ordering': ['-created'], 'verbose_name': 'Subsidy', 'verbose_name_plural': 'Subsidies'},
        ),
    ]
